version: '3.3'

services:

   databaseTR:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
       MYSQL_DATABASE: "${DB_NAME}"
       MYSQL_USER: "${DB_USER}"
       MYSQL_PASSWORD: "${DB_PASSWORD}"

   wordpressTR:
     depends_on:
       - databaseTR
     image: wordpress:5.2
     volumes:
        - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
        - ./htdocs:/var/www/html
     ports:
       - "80:80"
       - "443:443"
     restart: always
     environment:
       WORDPRESS_DB_HOST: databaseTR
       WORDPRESS_DB_NAME: "${DB_NAME}"
       WORDPRESS_DB_USER: "${DB_USER}"
       WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"

   phpmyadminTR:
     depends_on:
       - databaseTR
     image: phpmyadmin/phpmyadmin
     ports:
       - "8080:80"
     restart: always
     environment:
       PMA_HOST: databaseTR
       MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

volumes:
    htdocs:
    db_data: